import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const nome = "Yuri Oliveira";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portifólio | Yuri Oliveira</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* css */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" cross-origin />
        <link href="https://fonts.googleapis.com/css2?family=Lekton:ital,wght@0,400;0,700;1,400&family=Montserrat:wght@200&family=Roboto:ital@1&display=swap" rel="stylesheet" />
      </Head>
      <main>
        <div className="hero">
          <div className="hero--content">
        <div style={{ display: 'inline-block',float:'right', marginTop: '15px', marginLeft: '10px'}}>
        <iframe width="700px" height="450px" src="https://www.youtube.com/embed/fV6yoqY9bmE?si=8WjTFKOsiGPjvp0m" title="YouTube video player" frame-border="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allow-fullscreen />
            </div>
            <p className={`${styles.subtitle}`}>Olá, seja bem vindo ao meu portifólio</p>
            <p className={`${styles.title}`}>sou</p><h1 className={`${styles.nome}`}>{nome} :)</h1>
            <br></br><br></br>
            <h2 className={`${styles.title}`}>Sobre mim</h2>
            <p className={`${styles.descricao}`}>
              Último ano em <strong><em>Análise e Desenvolvimento de Sistemas</em></strong>
            </p>
            <p className={`${styles.descricao}`}>
              <strong><em>Brasileiro</em></strong>
            </p>
            <p className={`${styles.descricao}`}>
              <strong><em>Nascido em 2003</em></strong>
            </p>
            <p className={`${styles.subtitle}`}>Habilidades</p>
            <ul>
              <li className={`${styles.lista} ${styles.descricao}`}>React e React Native</li>
              <li className={`${styles.lista} ${styles.descricao}`}>Wordpress</li>
              <li className={`${styles.lista} ${styles.descricao}`}>PHP</li>
              <li className={`${styles.lista} ${styles.descricao}`}>Android</li>
              <li className={`${styles.lista} ${styles.descricao}`}>MYSQL</li>
              <li className={`${styles.lista} ${styles.descricao}`}>JavaScript & Typescript</li>
            </ul>
          </div>
          <br></br><br></br>
          <div className="hero--content2">
            <h2 className={`${styles.title}`} style={{ display: 'inline-block' }}>Projetos desenvolvidos</h2>
            <div className={`${styles.box}`}>
              <div>
                <p>oi</p>
              </div>
              <div>
                <p>oi</p>
              </div>
              <div>
                <p>oi</p>
              </div>
              <div>
                <p>oi</p>
              </div>
            </div>
          </div>
          <Image src="/image/portifolio-bg.jpg" alt="background" fill={true} className="bg-image" />
        </div>
      </main>
    </>
  );
}
